name: c3dev
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - nodejs
  - nb_conda_kernels
  - openmpi
  - mpi4py
  - pip
  - python>=3.7
  - readline
  - scipy
  - plotly-orca
  - psutil
  - pip:
    - --editable ../Cogent3/[dev]
    - --editable .
