name: c3dev
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - nodejs
  - jupyterlab
  - ipykernel
  - ipywidgets
  - nb_conda_kernels
  - openmpi
  - mpi4py
  - matplotlib
  - numpy
  - pip
  - python=3.7
  - readline
  - scipy
  - plotly
  - plotly-orca
  - psutil
  - pip:
    - click
    - jupyter_nbextensions_configurator
    - jupyterlab_code_formatter
    - pandas
    - sphinx
    - pytest
    - tqdm
    - --editable ../PyCogent3Apps/ 
    - --editable .
