name: c3dev
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - nodejs
  - jupyterlab
  - ipykernel
  - ipywidgets
  - nb_conda_kernels
  - openmpi
  - mpi4py
  - pip
  - numpy
  - python=3.7
  - readline
  - scipy
  - plotly
  - plotly-orca
  - psutil
  - pip:
    - click
    - jupyter_nbextensions_configurator
    - jupyterlab_code_formatter
    - pandas
    - sphinx
    - sphinx_rtd_theme
    - sphinx-autobuild
    - nbsphinx
    - jupytext
    - sphinxcontrib-bibtex
    - pytest
    - pytest-cov
    - tqdm
    - tox
    - scitrack
    - black
    - isort
    - tinydb
    - --editable ../PyCogent3Apps/ 
    - --editable .
